package antoniogiovanni.marchese.TEAM4BW5.enums;

public enum StatoFattura {
    BOZZA, DA_APPROVARE, PAGATA, DA_PAGARE, PAGATA_PARZIALMENTE, IN_RITARDO, ANNULLATA, IN_LAVORAZIONE, IN_SPEDIZIONE, ARCHIVIATA
}
